import './styles.css';

type Settings = { hotelName: string; motd: string; registrationsEnabled: boolean; maintenanceEnabled: boolean };
type Overview = { settings: Settings; server: { activeConnections: number; activeSessions: number; activeRooms: number; activeRoomUsers: number } };
type ThemeId = 'neon-purple' | 'tropical-blue' | 'sunset-pink' | 'cosmic-blue';
type ThemeConfig = { theme: ThemeId; logoText: string; eyebrow: string; title: string; description: string; ctaText: string; ctaVisible: boolean; institutionalText: string; institutionalUrl: string; primaryColor: string; secondaryColor: string; buttonColor: string; glassOpacity: number; blurPixels: number; cardOpacity: number; glowIntensity: number; borderRadius: number; decorationsEnabled: boolean; assetUrl: string; heroAsset: string; version: number };
type ThemeEntry = { id: ThemeId; name: string; description: string; active: boolean; configuration: ThemeConfig };
type ThemesResponse = { activeTheme: ThemeId; activeVersion: number; themes: ThemeEntry[] };
type ApiError = { error?: { message?: string } };

const element = <T extends HTMLElement>(selector: string): T => { const found = document.querySelector<T>(selector); if (!found) throw new Error(`Elemento ausente: ${selector}`); return found; };
const settingsForm = element<HTMLFormElement>('#settings-form'); const nameInput = element<HTMLInputElement>('#hotel-name'); const motdInput = element<HTMLTextAreaElement>('#motd'); const registrationsInput = element<HTMLInputElement>('#registrations-enabled'); const maintenanceInput = element<HTMLInputElement>('#maintenance-enabled'); const refreshButton = element<HTMLButtonElement>('#refresh'); const saveButton = element<HTMLButtonElement>('#save'); const saveState = element<HTMLElement>('#save-state'); const feedback = element<HTMLElement>('#feedback');
const overviewView = element<HTMLElement>('#overview-view'); const themesView = element<HTMLElement>('#themes-view'); const themeCards = element<HTMLElement>('#theme-cards'); const themeStatus = element<HTMLElement>('#theme-status'); const themeForm = element<HTMLFormElement>('#theme-form'); const themeSelect = element<HTMLSelectElement>('#theme-select'); const restoreButton = element<HTMLButtonElement>('#restore-theme'); const uploadButton = element<HTMLButtonElement>('#upload-asset'); const assetInput = element<HTMLInputElement>('#theme-asset'); const assetState = element<HTMLElement>('#asset-state'); const saveThemeButton = element<HTMLButtonElement>('#save-theme'); const previewDialog = element<HTMLDialogElement>('#preview-dialog'); const previewFrame = element<HTMLIFrameElement>('#preview-frame'); const previewFrameWrap = element<HTMLElement>('#preview-frame-wrap'); const previewTitle = element<HTMLElement>('#preview-title'); const previewRegister = element<HTMLButtonElement>('#preview-register'); const previewFullscreen = element<HTMLButtonElement>('#preview-fullscreen');
const themeInputs = { logoText: element<HTMLInputElement>('#logo-text'), eyebrow: element<HTMLInputElement>('#theme-eyebrow'), title: element<HTMLInputElement>('#theme-title'), description: element<HTMLTextAreaElement>('#theme-description'), ctaText: element<HTMLInputElement>('#cta-text'), institutionalText: element<HTMLInputElement>('#institutional-text'), institutionalUrl: element<HTMLInputElement>('#institutional-url'), primaryColor: element<HTMLInputElement>('#primary-color'), secondaryColor: element<HTMLInputElement>('#secondary-color'), buttonColor: element<HTMLInputElement>('#button-color'), glassOpacity: element<HTMLInputElement>('#glass-opacity'), blurPixels: element<HTMLInputElement>('#blur-pixels'), cardOpacity: element<HTMLInputElement>('#card-opacity'), glowIntensity: element<HTMLInputElement>('#glow-intensity'), borderRadius: element<HTMLInputElement>('#border-radius'), ctaVisible: element<HTMLInputElement>('#cta-visible'), decorationsEnabled: element<HTMLInputElement>('#decorations-enabled') };
const outputIds: Record<'glassOpacity' | 'blurPixels' | 'cardOpacity' | 'glowIntensity' | 'borderRadius', string> = { glassOpacity: '#glass-output', blurPixels: '#blur-output', cardOpacity: '#card-output', glowIntensity: '#glow-output', borderRadius: '#radius-output' };
let themes: ThemesResponse | null = null; let previewTheme: ThemeId | null = null; let previewRegisterMode = false;

function feedbackMessage(message: string, kind: 'error' | 'success' | 'info' = 'info'): void { feedback.textContent = message; feedback.dataset.kind = kind; }
function setSettingsBusy(busy: boolean): void { saveButton.disabled = busy; refreshButton.disabled = busy; saveButton.textContent = busy ? 'Salvando…' : 'Salvar alterações'; }
function setThemeBusy(busy: boolean): void { saveThemeButton.disabled = busy; restoreButton.disabled = busy; uploadButton.disabled = busy; themeSelect.disabled = busy; }
function populate(settings: Settings): void { nameInput.value = settings.hotelName; motdInput.value = settings.motd; registrationsInput.checked = settings.registrationsEnabled; maintenanceInput.checked = settings.maintenanceEnabled; }
function setMetric(selector: string, value: number): void { element<HTMLElement>(selector).textContent = String(value); }
async function parseResponse<T>(response: Response): Promise<T> { const data = await response.json() as T & ApiError; if (!response.ok) throw new Error(data.error?.message ?? 'Não foi possível concluir a operação.'); return data; }
function activeEntry(): ThemeEntry { if (!themes) throw new Error('Temas ainda não foram carregados.'); const found = themes.themes.find((theme) => theme.id === themeSelect.value); if (!found) throw new Error('Tema não encontrado.'); return found; }
function updateOutputs(): void { (Object.keys(outputIds) as (keyof typeof outputIds)[]).forEach((key) => { element<HTMLOutputElement>(outputIds[key]).value = key === 'blurPixels' || key === 'borderRadius' ? `${themeInputs[key].value}px` : `${themeInputs[key].value}%`; }); }

async function loadOverview(): Promise<void> { setSettingsBusy(true); saveState.textContent = 'Atualizando'; try { const overview = await parseResponse<Overview>(await fetch('/admin-api/v1/overview', { cache: 'no-store' })); populate(overview.settings); setMetric('#active-connections', overview.server.activeConnections); setMetric('#active-sessions', overview.server.activeSessions); setMetric('#active-rooms', overview.server.activeRooms); setMetric('#active-users', overview.server.activeRoomUsers); saveState.textContent = 'Dados atualizados'; } catch (error) { saveState.textContent = 'Indisponível'; feedbackMessage(error instanceof Error ? error.message : 'Não foi possível carregar o painel.', 'error'); } finally { setSettingsBusy(false); } }
function renderThemeOptions(): void { if (!themes) return; const selected = themeSelect.value || themes.activeTheme; themeSelect.replaceChildren(); themes.themes.forEach((theme) => { const option = document.createElement('option'); option.value = theme.id; option.textContent = `${theme.name}${theme.active ? ' — ativo' : ''}`; themeSelect.append(option); }); themeSelect.value = selected; populateThemeForm(activeEntry().configuration); }
function populateThemeForm(configuration: ThemeConfig): void { themeInputs.logoText.value = configuration.logoText; themeInputs.eyebrow.value = configuration.eyebrow; themeInputs.title.value = configuration.title; themeInputs.description.value = configuration.description; themeInputs.ctaText.value = configuration.ctaText; themeInputs.institutionalText.value = configuration.institutionalText; themeInputs.institutionalUrl.value = configuration.institutionalUrl; themeInputs.primaryColor.value = configuration.primaryColor; themeInputs.secondaryColor.value = configuration.secondaryColor; themeInputs.buttonColor.value = configuration.buttonColor; themeInputs.glassOpacity.value = String(configuration.glassOpacity); themeInputs.blurPixels.value = String(configuration.blurPixels); themeInputs.cardOpacity.value = String(configuration.cardOpacity); themeInputs.glowIntensity.value = String(configuration.glowIntensity); themeInputs.borderRadius.value = String(configuration.borderRadius); themeInputs.ctaVisible.checked = configuration.ctaVisible; themeInputs.decorationsEnabled.checked = configuration.decorationsEnabled; assetState.textContent = configuration.heroAsset === 'default' ? 'Usando arte padrão' : 'Imagem personalizada ativa'; assetInput.value = ''; updateOutputs(); }
function button(label: string, className: string, action: () => void): HTMLButtonElement { const result = document.createElement('button'); result.type = 'button'; result.className = className; result.textContent = label; result.addEventListener('click', action); return result; }
function renderThemeCards(): void { if (!themes) return; themeCards.replaceChildren(); themes.themes.forEach((theme) => { const card = document.createElement('article'); card.className = `theme-card${theme.active ? ' active' : ''}`; const thumbnail = document.createElement('img'); thumbnail.className = 'theme-thumb'; thumbnail.src = `/themes/${theme.id}.webp`; thumbnail.width = 164; thumbnail.height = 127; thumbnail.alt = `Prévia de ${theme.name}`; const content = document.createElement('div'); const heading = document.createElement('h3'); heading.textContent = theme.name; const description = document.createElement('p'); description.textContent = theme.description; const id = document.createElement('p'); id.className = 'theme-id'; id.textContent = theme.id; const status = document.createElement('span'); status.className = `status${theme.active ? ' active' : ''}`; status.textContent = theme.active ? 'Tema ativo' : 'Inativo'; const actions = document.createElement('div'); actions.className = 'card-buttons'; actions.append(button('Visualizar', 'small-button', () => openPreview(theme.id)), button('Personalizar', 'small-button', () => { themeSelect.value = theme.id; populateThemeForm(theme.configuration); element<HTMLElement>('.theme-editor').scrollIntoView({ behavior: 'smooth', block: 'start' }); })); if (!theme.active) actions.append(button('Ativar', 'small-button activate', () => { void activateTheme(theme); })); content.append(heading, description, id, status, actions); card.append(thumbnail, content); themeCards.append(card); }); }
async function loadThemes(): Promise<void> { themeStatus.textContent = 'Atualizando temas'; try { themes = await parseResponse<ThemesResponse>(await fetch('/admin-api/v1/login-themes', { cache: 'no-store' })); renderThemeCards(); renderThemeOptions(); themeStatus.textContent = `Ativo: ${themes.themes.find((theme) => theme.id === themes!.activeTheme)?.name ?? themes.activeTheme}`; } catch (error) { themeStatus.textContent = 'Indisponível'; feedbackMessage(error instanceof Error ? error.message : 'Não foi possível carregar os temas.', 'error'); } }
async function activateTheme(theme: ThemeEntry): Promise<void> { if (!window.confirm(`Ativar “${theme.name}” na página pública agora? Sessões já autenticadas não serão interrompidas.`)) return; setThemeBusy(true); try { themes = await parseResponse<ThemesResponse>(await fetch(`/admin-api/v1/login-themes/${theme.id}/activate`, { method: 'POST' })); renderThemeCards(); renderThemeOptions(); themeStatus.textContent = `Ativo: ${theme.name}`; feedbackMessage(`Tema “${theme.name}” ativado e publicado.`, 'success'); } catch (error) { feedbackMessage(error instanceof Error ? error.message : 'Não foi possível ativar o tema.', 'error'); } finally { setThemeBusy(false); } }
function formBody(): URLSearchParams { return new URLSearchParams({ logoText: themeInputs.logoText.value, eyebrow: themeInputs.eyebrow.value, title: themeInputs.title.value, description: themeInputs.description.value, ctaText: themeInputs.ctaText.value, ctaVisible: String(themeInputs.ctaVisible.checked), institutionalText: themeInputs.institutionalText.value, institutionalUrl: themeInputs.institutionalUrl.value, primaryColor: themeInputs.primaryColor.value, secondaryColor: themeInputs.secondaryColor.value, buttonColor: themeInputs.buttonColor.value, glassOpacity: themeInputs.glassOpacity.value, blurPixels: themeInputs.blurPixels.value, cardOpacity: themeInputs.cardOpacity.value, glowIntensity: themeInputs.glowIntensity.value, borderRadius: themeInputs.borderRadius.value, decorationsEnabled: String(themeInputs.decorationsEnabled.checked) }); }
function replaceTheme(configuration: ThemeConfig): void { if (!themes) return; themes = { ...themes, themes: themes.themes.map((theme) => theme.id === configuration.theme ? { ...theme, configuration } : theme) }; renderThemeCards(); renderThemeOptions(); }
function openPreview(theme: ThemeId): void { previewTheme = theme; previewRegisterMode = false; previewTitle.textContent = `Prévia real · ${themes?.themes.find((entry) => entry.id === theme)?.name ?? theme}`; previewFrame.src = `/?preview=${theme}`; if (!previewDialog.open) previewDialog.showModal(); }

settingsForm.addEventListener('submit', (event) => { event.preventDefault(); if (!settingsForm.reportValidity()) return; setSettingsBusy(true); saveState.textContent = 'Salvando'; const body = new URLSearchParams({ hotelName: nameInput.value, motd: motdInput.value, registrationsEnabled: String(registrationsInput.checked), maintenanceEnabled: String(maintenanceInput.checked) }); void (async () => { try { const settings = await parseResponse<Settings>(await fetch('/admin-api/v1/settings', { method: 'PUT', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body })); populate(settings); saveState.textContent = 'Salvo agora'; feedbackMessage('Configuração salva e aplicada.', 'success'); } catch (error) { saveState.textContent = 'Não salvo'; feedbackMessage(error instanceof Error ? error.message : 'Não foi possível salvar a configuração.', 'error'); } finally { setSettingsBusy(false); } })(); });
themeForm.addEventListener('submit', (event) => { event.preventDefault(); if (!themeForm.reportValidity()) return; const selected = activeEntry(); if (!window.confirm(`Salvar a personalização de “${selected.name}”?`)) return; setThemeBusy(true); void (async () => { try { const saved = await parseResponse<ThemeConfig>(await fetch(`/admin-api/v1/login-themes/${selected.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: formBody() })); replaceTheme(saved); feedbackMessage('Personalização salva.', 'success'); } catch (error) { feedbackMessage(error instanceof Error ? error.message : 'Não foi possível salvar a personalização.', 'error'); } finally { setThemeBusy(false); } })(); });
restoreButton.addEventListener('click', () => { const selected = activeEntry(); if (!window.confirm(`Restaurar o padrão de “${selected.name}”? A imagem personalizada deste tema será removida.`)) return; setThemeBusy(true); void (async () => { try { const saved = await parseResponse<ThemeConfig>(await fetch(`/admin-api/v1/login-themes/${selected.id}/restore`, { method: 'POST' })); replaceTheme(saved); feedbackMessage('Tema restaurado ao padrão.', 'success'); } catch (error) { feedbackMessage(error instanceof Error ? error.message : 'Não foi possível restaurar o tema.', 'error'); } finally { setThemeBusy(false); } })(); });
uploadButton.addEventListener('click', () => { const file = assetInput.files?.[0]; if (!file) { feedbackMessage('Escolha uma imagem PNG ou JPEG antes de enviar.', 'error'); return; } if (!['image/png', 'image/jpeg'].includes(file.type) || file.size > 2_000_000) { feedbackMessage('A imagem deve ser PNG ou JPEG de até 2 MB.', 'error'); return; } const selected = activeEntry(); setThemeBusy(true); void (async () => { try { const saved = await parseResponse<ThemeConfig>(await fetch(`/admin-api/v1/login-themes/${selected.id}/asset`, { method: 'POST', headers: { 'Content-Type': file.type }, body: file })); replaceTheme(saved); feedbackMessage('Imagem validada e publicada para este tema.', 'success'); } catch (error) { feedbackMessage(error instanceof Error ? error.message : 'Não foi possível enviar a imagem.', 'error'); } finally { setThemeBusy(false); } })(); });
themeSelect.addEventListener('change', () => populateThemeForm(activeEntry().configuration)); (Object.keys(outputIds) as (keyof typeof outputIds)[]).forEach((key) => themeInputs[key].addEventListener('input', updateOutputs));
document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach((tab) => tab.addEventListener('click', () => { const themesSelected = tab.dataset.view === 'themes'; overviewView.hidden = themesSelected; themesView.hidden = !themesSelected; document.querySelectorAll('.tab').forEach((item) => item.classList.toggle('active', item === tab)); }));
document.querySelectorAll<HTMLButtonElement>('[data-preview-mode]').forEach((button) => button.addEventListener('click', () => { previewFrameWrap.className = `preview-frame-wrap ${button.dataset.previewMode}`; })); previewFullscreen.addEventListener('click', () => { void previewDialog.requestFullscreen?.(); }); previewRegister.addEventListener('click', () => { if (!previewTheme) return; previewRegisterMode = !previewRegisterMode; previewRegister.textContent = previewRegisterMode ? 'Login' : 'Cadastro'; previewFrame.src = `/?preview=${previewTheme}&mode=${previewRegisterMode ? 'register' : 'login'}`; }); element<HTMLButtonElement>('#close-preview').addEventListener('click', () => previewDialog.close()); previewDialog.addEventListener('click', (event) => { if (event.target === previewDialog) previewDialog.close(); });
refreshButton.addEventListener('click', () => { void Promise.all([loadOverview(), loadThemes()]); }); void Promise.all([loadOverview(), loadThemes()]);
